### ISSUE TITLE
Algo Provider python module

### ISSUE THREAD

**Issue by FadyCoding** [debiai/easy-algo-provider#1]
**Describe the solution you'd like**
Implement a python module that is compliant with the existing Algo Provider API.

**Describe alternatives you've considered**

**TODO**

- [x] Integrate AlgoProvider API into a python module
- [x] Launch an algoprovider from the new module
- [x] Implement specific logic for the package to work with the new DocString method
- [ ] Make sure tests are through (pipeline, docker, python module)
- [ ] Documentation
- [ ] Suggest a visual interface for the module when functional
